### ISSUE TITLE
Please check the argon.min.css file in your ZIP file.

### ISSUE THREAD

**Issue by cocoori1** [creativetimofficial/ct-argon-dashboard-pro-nodejs#2]
Dear creative-tim

Thank you for your technical support.

We purchased the Argon Dashboard Pro Nodejs, and downloaded argon-dashboard-pro-nodejs-v1.0.1.zip file in your website. But we can't find argon.min.css in pro version zip file so root page is crashed. Could you check this problem?

**Comment by supportudevoffice** [comment]
Hello @cocoori1 

This is probably caused because `gulp` did not run. You can try the following:

1. Start the app using `npm run dev` which also starts `gulp` and creates the `argon.min.css` file that you are missing.
2. Start the app using `npm start` and then start gulp using `npm run gulp` 

Let us know if you need further assistance.
Thank you!
